# Generated by Django 4.2.3 on 2023-07-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_studio_movie_picture_studiomoviepicture_studio_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAudition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('selection_status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='home.artist')),
                ('audition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='home.audition')),
            ],
        ),
    ]
