# Generated by Django 4.2.3 on 2023-08-01 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_register_signup_artist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='booking_status',
        ),
        migrations.CreateModel(
            name='ArtistBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_booking', to='home.artist')),
            ],
        ),
    ]
