# Generated by Django 4.2.3 on 2023-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_artist_booking_status_artistbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='UserDetail',
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='booking_studio',
            field=models.CharField(choices=[('accept', 'Accept'), ('deny', 'Deny'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
