# Generated by Django 4.2.3 on 2023-08-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_signup_userdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='story_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
