# Generated by Django 4.2.3 on 2023-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_audition_story_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistbooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='no_of_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='studio_booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
