# Generated by Django 4.2.3 on 2023-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_artistbooking_booking_date_studiobooking_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiobooking',
            name='studio_booking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
