# Generated by Django 4.2.3 on 2023-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_studiobooking_studio_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistbooking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
